### ISSUE TITLE
installation error

### ISSUE THREAD

**Issue by UddeshyaPandey** [imAIgene-Dream3D/BGT#2]
I was trying to install the singularity image
 ## at step 5
uddeshya@LAPTOP-SNHQ6L1T:~/test_bgt/singularity/builddir$ singularity shell --pid bgt_image.sif

## Error
FATAL:   could not open image /home/uddeshya/test_bgt/singularity/builddir/bgt_image.sif: failed to retrieve path for /home/uddeshya/test_bgt/singularity/builddir/bgt_image.sif: lstat /home/uddeshya/test_bgt/singularity/builddir/bgt_image.sif: no such file or directory

my current directory
/home/uddeshya/test_bgt/singularity/builddir

i am using windows 11

**Comment by miguelhroca** [comment]
Can you try to do chmod +x bgt_image.sif and make sure that the file exist in that directory? 
And try to execute it again

**Comment by UddeshyaPandey** [comment]
Solved
